apiVersion: v1
kind: Service
metadata:
  name: simple-api-node
  labels:
    app: simple-api-node
spec:
  selector:
    app: simple-api-node
  ports:
    - port: 8000
      targetPort: 8080
      protocol: TCP
      name: http
  type: NodePort